import type { Metadata } from 'next'
import { Fondamento, Martel, Poppins, Roboto } from 'next/font/google'
import '@/styles/global/tokens.scss'
import '@/styles/global/resets.scss'
import '@/styles/global/layout.scss'
import '@/styles/global/typography.scss'

import Layout from '@/components/Layout'

const fondamento = Fondamento({
  weight: ['400'],
  subsets: ['latin-ext'],
  variable: '--qx-text-face-fondamento',
})

const martel = Martel({
  weight: ['300', '400', '600', '700'],
  subsets: ['latin-ext'],
  variable: '--qx-text-face-martel',
})

const poppins = Poppins({
  weight: ['300', '400', '600', '700'],
  subsets: ['latin-ext'],
  variable: '--qx-text-face-poppins',
})

const roboto = Roboto({
  preload: true,
  weight: ['300', '400', '700'],
  subsets: ['latin-ext'],
  variable: '--qx-text-face-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${fondamento.variable} ${martel.variable} ${poppins.variable} ${roboto.variable} ${roboto.className}`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
