import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const mockPlayers = (accountId: number) => {
  return [
    {
      name: 'Rook Sample',
      group_id: 1,
      account_id: accountId,
      level: 2,
      vocation: 0,
      health: 155,
      healthmax: 155,
      experience: BigInt(100),
      lookbody: 113,
      lookfeet: 115,
      lookhead: 95,
      looklegs: 39,
      looktype: 129,
      maglevel: 2,
      mana: 60,
      manamax: 60,
      manaspent: BigInt(5936),
      town_id: 1,
      conditions: Buffer.from(''),
      cap: 410,
      sex: 1,
      skill_club: 12,
      skill_club_tries: BigInt(155),
      skill_sword: 12,
      skill_sword_tries: BigInt(155),
      skill_axe: 12,
      skill_axe_tries: BigInt(155),
      skill_dist: 12,
      skill_dist_tries: BigInt(93),
    },
    {
      name: 'Sorcerer Sample',
      group_id: 1,
      account_id: accountId,
      level: 8,
      vocation: 1,
      health: 185,
      healthmax: 185,
      experience: BigInt(4200),
      lookbody: 113,
      lookfeet: 115,
      lookhead: 95,
      looklegs: 39,
      looktype: 129,
      maglevel: 0,
      mana: 90,
      manamax: 90,
      manaspent: BigInt(0),
      town_id: 8,
      conditions: Buffer.from(''),
      cap: 470,
      sex: 1,
      skill_club: 10,
      skill_club_tries: BigInt(0),
      skill_sword: 10,
      skill_sword_tries: BigInt(0),
      skill_axe: 10,
      skill_axe_tries: BigInt(0),
      skill_dist: 10,
      skill_dist_tries: BigInt(0),
    },
    {
      name: 'Druid Sample',
      group_id: 1,
      account_id: accountId,
      level: 8,
      vocation: 2,
      health: 185,
      healthmax: 185,
      experience: BigInt(4200),
      lookbody: 113,
      lookfeet: 115,
      lookhead: 95,
      looklegs: 39,
      looktype: 129,
      maglevel: 0,
      mana: 90,
      manamax: 90,
      manaspent: BigInt(0),
      town_id: 8,
      conditions: Buffer.from(''),
      cap: 470,
      sex: 1,
      skill_club: 10,
      skill_club_tries: BigInt(0),
      skill_sword: 10,
      skill_sword_tries: BigInt(0),
      skill_axe: 10,
      skill_axe_tries: BigInt(0),
      skill_dist: 10,
      skill_dist_tries: BigInt(0),
    },
    {
      name: 'Paladin Sample',
      group_id: 1,
      account_id: accountId,
      level: 8,
      vocation: 3,
      health: 185,
      healthmax: 185,
      experience: BigInt(4200),
      lookbody: 113,
      lookfeet: 115,
      lookhead: 95,
      looklegs: 39,
      looktype: 129,
      maglevel: 0,
      mana: 90,
      manamax: 90,
      manaspent: BigInt(0),
      town_id: 8,
      conditions: Buffer.from(''),
      cap: 470,
      sex: 1,
      skill_club: 10,
      skill_club_tries: BigInt(0),
      skill_sword: 10,
      skill_sword_tries: BigInt(0),
      skill_axe: 10,
      skill_axe_tries: BigInt(0),
      skill_dist: 10,
      skill_dist_tries: BigInt(0),
    },
    {
      name: 'Knight Sample',
      group_id: 1,
      account_id: accountId,
      level: 8,
      vocation: 4,
      health: 185,
      healthmax: 185,
      experience: BigInt(4200),
      lookbody: 113,
      lookfeet: 115,
      lookhead: 95,
      looklegs: 39,
      looktype: 129,
      maglevel: 0,
      mana: 90,
      manamax: 90,
      manaspent: BigInt(0),
      town_id: 8,
      conditions: Buffer.from(''),
      cap: 470,
      sex: 1,
      skill_club: 10,
      skill_club_tries: BigInt(0),
      skill_sword: 10,
      skill_sword_tries: BigInt(0),
      skill_axe: 10,
      skill_axe_tries: BigInt(0),
      skill_dist: 10,
      skill_dist_tries: BigInt(0),
    },
    {
      name: '[GM] Kamity',
      group_id: 6,
      account_id: accountId,
      level: 8,
      vocation: 0,
      health: 185,
      healthmax: 185,
      experience: BigInt(4200),
      lookbody: 113,
      lookfeet: 115,
      lookhead: 95,
      looklegs: 39,
      looktype: 75,
      maglevel: 0,
      mana: 90,
      manamax: 90,
      manaspent: BigInt(0),
      town_id: 8,
      conditions: Buffer.from(''),
      cap: 470,
      sex: 1,
      skill_club: 10,
      skill_club_tries: BigInt(0),
      skill_sword: 10,
      skill_sword_tries: BigInt(0),
      skill_axe: 10,
      skill_axe_tries: BigInt(0),
      skill_dist: 10,
      skill_dist_tries: BigInt(0),
    },
  ]
}

export const main = async (): Promise<void> => {
  const user = await prisma.accounts.create({
    data: {
      name: 'god',
      email: '@god',
      password: '21298df8a3277357ee55b01df9530b535cf08ec1', // god
      type: 5,
    },
  })

  await prisma.players.createMany({
    data: mockPlayers(user.id),
  })
}

main()
  .catch((e) => {
    console.log(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
